//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace handling_projects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClanTIma
    {
        public int idKorisnickiRacun { get; set; }
        public int idTima { get; set; }
        public bool vodja { get; set; }
    
        public virtual KorisnickiRacun KorisnickiRacun { get; set; }
        public virtual Tim Tim { get; set; }
    }
}
